64-bit, osx: implement cross-plat __debugbreak()
__debugbreak is a MSVC instrinsic, which strangely enough is also
implemented in apple clang (and in vanilla clang, with -fms-extensions, but
this has its own problems). Not
in gcc as far as I know.

Luckily, there's a liberally licensed header file by Scott Tsai which takes
care of the cross platform (ARM/x86/x64) and cross-compiler issues.

https://github.com/scottt/debugbreak

debugbreak.h was taken from that 2-clause BSD-licensed project.

Other references:

Is there a portable equivalent to DebugBreak()/__debugbreak?
http://stackoverflow.com/questions/173618/is-there-a-portable-equivalent-to-debugbreak-debugbreak

__debugbreak() in apple clang but not vanilla, how to detect
http://stackoverflow.com/questions/25792878/debugbreak-in-apple-clang-but-not-vanilla-how-to-detect

The build error this patch solves (OSX/clang) is listed below. The reason it
happens is because on apple clang, __debugbreak is already declared.

[  1%] Building CXX object common/src/Utilities/CMakeFiles/Utilities.dir/AlignedMalloc.cpp.o
In file included from common/src/Utilities/AlignedMalloc.cpp:19:
In file included from common/src/Utilities/./PrecompiledHeader.h:21:
In file included from common/include/Utilities/Dependencies.h:193:
In file included from common/include/Pcsx2Defs.h:32:
common/include/intrin_x86.h:104:55: error: static declaration of '__debugbreak' follows non-static declaration
static __inline__ __attribute__((always_inline)) void __debugbreak(void)